### ISSUE TITLE
discrepancy w/ Florentine Bronze (+more?) TFC Metallum recipe information + actual recipe displayed by JEI

### ISSUE THREAD

**Issue by ghost** [Mrthomas20121-Mods/TFC-Metallum#20]
More of a _minor discrepancy_, but the recipe outlined in the guide book for the mod is different from the recipe the mod actually uses
<img width="649" alt="Screenshot 2024-05-08 at 8 15 07 PM" src="https://github.com/Mrthomas20121-Mods/TFC-Metallum/assets/34328618/eac6b9de-aba7-4ccb-82c4-4e63b9096cf3">
<img width="389" alt="Screenshot 2024-05-08 at 8 15 48 PM" src="https://github.com/Mrthomas20121-Mods/TFC-Metallum/assets/34328618/befe5c86-2185-4ced-8ca1-09a61cac5e1e">

Note I am playing on a modpack (SeriousFirmaCraft 1.18.2) but TFC Metallum does _not_ come with this modpack by default so no recipes have been changed by it.

As per the last issue I posted, I have not checked other recipes but its possible there are more. Completely a cosmetic issue/non-issue nevertheless

**Comment by Mrthomas20121** [comment]
it was changed and I forgot to change it in the book
