### ISSUE TITLE
unable to cast some molten metals

### ISSUE THREAD

**Issue by velocityraptor-real** [Mrthomas20121-Mods/TFC-Metallum#4]
Some materials (for example boron and iridium) have higher default melting points set than the tfc crucible can reach. When their melting points are lowered with a datapack, the items successfully melt. However, the molten metal refuses to be cast into any mold. Any ideas what might prevent this from happening?

Summary:
Forge version: 40.2.1
Mod version: 1.0.3

Expected behaviour:
All molten metals can be casted into atleast the ingot mold

Observed behaviour:
Molten metals with high melting points, which have to be reduced via datapack to melt in crucible, cannot be cast into any mold.

Example screenshot:
![2023-04-19_22 49 34](https://user-images.githubusercontent.com/56190563/233196869-7ef824bd-9e1a-4d73-8036-eade273c5728.png)

**Comment by Mrthomas20121** [comment]
just so you know the high melting point is normal. i'm unsure why this would not work, i'll look into it
