### ISSUE TITLE
name of metal knife item category incorrect

### ISSUE THREAD

**Issue by billyma6** [Mrthomas20121-Mods/TFC-Metallum#5]
the item tag/name for the knives are incorrectly spelt in comparison to the TFC TNG knives. the items have the "tfc:knifes" tag when it should be instead "tfc:knives" to match the others. Right now, none of them can be used as knives in crafting.

**Comment by Mrthomas20121** [comment]
i know, it's already fixed in dev

**Comment by chemlzh** [comment]
It seems that the ver 1.0.4 pack has not been upload to either GitHub or CurseForge, so does it mean I need to compile the new version myself?
