### ISSUE TITLE
Cannot find weak tungsten steel or its alloy mixing recipe in version 1.0.3

### ISSUE THREAD

**Issue by chemlzh** [Mrthomas20121-Mods/TFC-Metallum#7]
I have download TFC Metallum 1.0.3 from Curseforge (https://www.curseforge.com/minecraft/mc-mods/tfcm/files/4449385), and according to its description, it has implemented tungsten steel and weak tungsten steel. However, I cannot find any item concerned with weak tungsten steel (molten alloy, alloy ingot, etc.), or alloy mixing recipe to produce weak tungsten steel. And we all know tungsten steel ingots are produced by forging weak tungsten steel (like black steel production), therefore it's impossible for us to produce tungsten ingots.
So are weak tungsten steel (and its production) really implemented? If not, is this a bug in version 1.0.3?

**Comment by Mrthomas20121** [comment]
weak tungsten steel was never added(despite what i said on cf) and the production of tungsten steel not implemented.

**Comment by Mrthomas20121** [comment]
the texture for weak tungsten steel exists but i never implemented it

**Comment by chemlzh** [comment]
Then how can we obtain tungsten steel by mixing metals (without cheating)? Should we need to add recipe by using CraftTweaker?

**Comment by Mrthomas20121** [comment]
yes you should
