### ISSUE TITLE
Andesite alloy is not craftable

### ISSUE THREAD

**Issue by Gata-chan** [Mrthomas20121-Mods/TFC-Metallum#8]
The andesite alloy ingot can obtained from molten andesite alloy but JEI has not recepie for how to craft molten andesite alloy. Not alloyng, not melting, nothing. 
 Am I missing something?
 
I do have Create installed and I am asking cause TFC Andesite is not compatable with Create recepies that require Minecraft Andesite so I though that TFC-Metallum would help, but it's another dead end

**Comment by Mrthomas20121** [comment]
there is no recipes to craft it. i should add one tbh

**Comment by Gata-chan** [comment]
Please do! I am at such a headscratcher right now, since I can't make the most basic thing in Create using TFC materials cause the there's simply no compat or compat mod for that, and diving into CraftTweaker just to change less that half a dozen recepies seems like such a pain (I've had a similar headscratcher with TFC Wheat that is not millable in Create Mill)
